@startuml Prepare OpenGL
actor       Android       as Android1 #green

Android1 -> SceneRenderer: new
activate SceneRenderer
group Load OpenGL shaders
SceneRenderer -> FileSystem: readTextFileContent(color_vertex_shader)
note over FileSystem
uniform mat4 u_Matrix;
attribute vec4 a_Position;
void main()
{
    gl_Position = u_Matrix * a_Position;
}
end note
FileSystem -> SceneRenderer: vertexShaderCode
SceneRenderer -> FileSystem: readTextFileContent(color_fragment_shader)
note over FileSystem #aqua
uniform vec4 u_Color;
void main()
{
    gl_FragColor = u_Color;
}
end note
FileSystem -> SceneRenderer: fragmentShaderCode

end

Android1 -> SceneRenderer: onSurfaceCreated

group Compile shaders & link them into "Program" to be run at GPU
SceneRenderer -> ShadersProgramBuilder: buildProgram(vertexShaderCode, fragmentShaderCode)

group Compile Vertex shader
ShadersProgramBuilder -> GLES20: glCreateShader
ShadersProgramBuilder -> GLES20: glShaderSource
ShadersProgramBuilder -> GLES20: glCompileShader
GLES20 -> ShadersProgramBuilder: vertexShaderId
end
group Compile Fragment shader
GLES20 -> ShadersProgramBuilder: fragmentShaderId
end

group Link OpenGL Program
ShadersProgramBuilder -> GLES20: glCreateProgram
ShadersProgramBuilder -> GLES20: glAttachShader(vertexShaderId)
ShadersProgramBuilder -> GLES20: glAttachShader(fragmentShaderId)
ShadersProgramBuilder -> GLES20: glLinkProgram
participant GPU as GPU #99FF99
GLES20 -> GPU: programToRun
GLES20 -> ShadersProgramBuilder: programObjectId
end

ShadersProgramBuilder -> SceneRenderer: programObjectId

end

group Retrieve "handles" of shader variables residing at GPU

SceneRenderer -> GLES20: glGetAttribLocation(programObjectId, a_Position)
GPU -> SceneRenderer: aPositionLocation
SceneRenderer -> GLES20: glGetUniformLocation(programObjectId, u_Matrix)
GPU -> SceneRenderer: uMatrixLocation

SceneRenderer -> GLES20: glGetUniformLocation(programObjectId, u_Color)
GPU -> SceneRenderer: uColorLocation
end
@enduml