@startuml Prepare OpenGL
actor       Android       as Android1 #green
participant SceneRenderer as SceneRenderer
participant Cuboid as Cuboid
participant VertexArray as VertexArray
participant GLES20 as GLES20
participant GPU as GPU #99FF99

Android1 -> SceneRenderer: onSurfaceCreated
activate SceneRenderer
SceneRenderer -> Cuboid: create Wall based on saved data
Cuboid -> VertexArray: new VertexArray(vertexData)
VertexArray -> VertexArray: allocate vertex data inside floatBuffer \n (vertices buffer)

Cuboid -> Cuboid: create vertex sequence  for drawing Faces \n and allocate it in ByteBuffer
note right Cuboid
OpenGL ES draws faces
composed out of triangles.
Cuboid has 6 faces
Each has 2 triangles of 3 vertices
end note
Cuboid -> Cuboid: create vertex sequence for drawing Edges \n and allocate it in ByteBuffer

Android1 -> SceneRenderer: onDrawFrame

SceneRenderer -> GLES20: glUseProgram(programObjectId)
note right GLES20
programObject consists of both fragment shader
 and vertex shader
end note
GLES20 -> GPU: select programToRun

SceneRenderer -> Cuboid: draw(aPositionLocation,\n          uColorLocation,\n          uMatrixLocation,\n          viewProjectionMatrix)
group prepare DataSource for "attribute" variable of shader
Cuboid -> VertexArray: setVertexAttribPointer(aPositionLocation)
VertexArray -> GLES20: glVertexAttribPointer(aPositionLocation,\n                                    vertices buffer)
note over GLES20
link vertices buffer
as input source for 3D shape
calculation inside GPU shader
end note
VertexArray -> GLES20: glEnableVertexAttribArray(aPositionLocation)
GLES20 -> GPU: pass vertices buffer for aPositionLocation
end

group set "uniform" Matrix variable of shader
Cuboid -> Cuboid: multiply world viewProjectionMatrix\nwith Cuboid internal model Matrix
Cuboid -> GLES20: glUniformMatrix4fv(uMatrixLocation, modelViewProjectionMatrix)
GLES20 -> GPU: set current Matrix for 3D shapes calculation
end

group set "uniform" Color variable of shader
Cuboid -> GLES20: glUniform4f(uColorLocation, edgeColor)
GLES20 -> GPU: set current "active" color
end

Cuboid -> GLES20: glDrawElements(GL_LINES, 24 indexes, vertexIndexesBuffer)
GLES20 -> GPU: pass indexes of vertices to build lines from
GLES20 -> GPU: draw lines of Cuboid edges

group set "uniform" Color variable of shader
Cuboid -> GLES20: glUniform4f(uColorLocation, faceColor)
GLES20 -> GPU: set current "active" color
end


Cuboid -> GLES20: glDrawElements(GL_TRIANGLES, 36 indexes, vertexIndexesBuffer)
GLES20 -> GPU: pass indexes of vertices to build triangles from
GLES20 -> GPU: draw triangles of Cuboid faces
@enduml